### ISSUE TITLE
require "survey" and "survival" packages in docker instance

### ISSUE THREAD

**Issue by chiragjp** [chiragjp/nhanes_scidata#1]
@nampho2 -- the analyses will need the survey and survival R packages; can you update the docker file if appropriate?

**Comment by npho** [comment]
Will do, working on trying to just include it straight out in the `xwas` package as a bundle. In either event it will be there for the release.

**Comment by npho** [comment]
The `survey` and `survival` R packages were added through `xwas` library dependencies in an update to that package. Demo below, resolving issue.

Load directly,

```
[vagrant@docker-vagrant ~]$ docker run -it chiragjp/nhanes_scidata /bin/bash
[root@77d4d149aa27 /]# su - rstudio
[rstudio@77d4d149aa27 ~]$ R
> library(survey, quietly=TRUE)

Attaching package: ‘survey’

The following object is masked from ‘package:graphics’:

    dotchart

> library(survival)
> 
```

Or through using `xwas`,

```
[rstudio@77d4d149aa27 ~]$ R
> library(xwas)
Loading required package: parallel
Loading required package: survey
Loading required package: grid

Attaching package: ‘survey’

The following object is masked from ‘package:graphics’:

    dotchart

Loading required package: survival
> 
```
